### ISSUE TITLE
Diet throws error on Node 6.0.0

### ISSUE THREAD

**Issue by peremenov** [adamhalasz/diet#39]
Example code:

```javascript
var server = require('diet');
var app  = server();
```

Result:
```
 Diet  (0.10.4) ☺
 http://dietjs.com/

/Users/kirill/Sites/realty/node_modules/diet/index.js:68
                initialized = true;
                            ^

TypeError: Assignment to constant variable.
    at Server (/Users/kirill/Sites/realty/node_modules/diet/index.js:68:29)
    at Object.<anonymous> (/Users/kirill/Sites/realty/index.js:9:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by adamhalasz** [comment]
Hey,

I just fixed this in v0.10.5. It was a small problem with the "initialized" variable being defined as constant in strict mode. Let me know if you have any other questions.

Thanks,
Adam
