### ISSUE TITLE
Configuring other templating engines

### ISSUE THREAD

**Issue by kokujin** [adamhalasz/diet#49]
I just tried to use the Nunjucks templating engine

``````
var nunjucks = require('nunjucks');

    nunjucks.configure(app.path+'/views/nunjucks/', {
        autoescape: true,
        express: app,
        watch: true
    });
    app.view('html', nunjucks.render);
``````
This does not work as expected, here is the error I received

`````
/home/kokujin/development/research/diet_test/node_modules/nunjucks/src/environment.js:287
        app.set('view', NunjucksView);
            ^

TypeError: app.set is not a function
  at Obj.extend.express (/home/kokujin/development/research/diet_test/node_modules/nunjucks/src/environment.js:287:13)
  at Object.module.exports.configure (/home/kokujin/development/research/diet_test/node_modules/nunjucks/index.js:54:11)
  at Object.<anonymous> (/home/kokujin/development/research/diet_test/index.js:33:14)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Function.Module.runMain (module.js:575:10)
  at startup (node.js:160:18)
  at node.js:449:3

``````
What should I look out for or what other steps should I take to properly configure other engines?

Thanks

**Comment by adamhalasz** [comment]
Hey @kokujin I createad a small example that works for me. Please have a look at this:
https://github.com/adamhalasz/diet/tree/master/examples/nunjucks

**Comment by kokujin** [comment]
Excellent! Works. Thanks
